application: fish-basket
module: default
version: 1
runtime: go
api_version: go1

automatic_scaling:
  min_idle_instances: 0
  max_pending_latency: 30ms
  max_concurrent_requests: 50

handlers:
- url: .*
  static_dir: nonexist

