application: fish-basket
module: default
version: 1
runtime: go
api_version: go1

handlers:
- url: '/components/(angular-ui-bootstrap|bootstrap|jquery)/(.*)'
  static_files: components/\1/dist/\2
  upload: components/.*

- url: '/components/angular(.*)'
  static_files: components/angular\1
  upload: components/.*

- url: /api/.*
  script: _go_app

- url: (.*)/
  static_files: ui\1/index.html
  upload: ui/.*.html

- url: /(.*)
  static_files: ui/\1.html
  upload: ui/.*.html

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^.*node_modules.*$
- ^.*Gruntfile.*$
- ^.*karma.*$
- ^.*\.md$
- ^.*\.json$
- ^.*\.gzip$
- ^.*angular-mocks.*$
- ^.*angular-scenario.*$
- ^components/(angular-ui-bootstrap|bootstrap|jquery)/(?!dist).*$
