application: fish-basket
module: default
version: 1
runtime: go
api_version: go1

handlers:
- url: '/components/(angular-ui-bootstrap|bootstrap|jquery)/(.*)'
  static_files: components/\1/dist/\2
  upload: components/.*

- url: '/components/angular(.*)'
  static_files: components/angular\1
  upload: components/.*

- url: /api/.*
  script: _go_app

- url: /(.*)\.(css|js|js.map)
  static_files: ui/\1.\2
  upload: ui/.*

- url: /
  static_files: ui/index.html
  upload: ui/.*

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^components/.*node_modules.*$
- ^components/.*Gruntfile.*$
- ^components/.*karma.*$
- ^components/.*\.md$
- ^components/.*\.json$
- ^components/.*\.gzip$
- ^components/angular-mocks.*$
- ^components/angular-scenario.*$
- ^components/(angular-ui-bootstrap|bootstrap|jquery)/(?!dist).*$
